salesforce/eslint-config-lwc

package.json
recommended.js
yarn.lock

Restrict usage of global properties attached on the window object

---

yarn.lock

Security vulnerabilities WS-2019-0063, CVE-2019-10744

chore: update trasitive dependency versions

---

base.js
package.json
yarn.lock

eslint-plugin-lwc to 0.8.0 contains new rule that prevents upper case leading characters in @api names. This rule is now consumed as part of the base configuration.

chore: upgarde eslint-plugin-lwc to 0.8.0

---

base.js
recommended.js

Since https://github.com/salesforce/lwc/pull/1687, LWC now capitalized public property names. 
This PR moves the `@lwc/lwc/no-leading-uppercase-api-name` linting rule from the `base` preset to the `recommended` preset.

feat: Move no-leading-uppercase-api-name to recommended preset

---

base.js
test/base.js

This PR adds and configures [@lwc/lwc/no-unknown-wire-adapters](https://github.com/salesforce/eslint-plugin-lwc/blob/master/docs/rules/no-unknown-wire-adapters.md) and [@lwc/lwc/no-unexpected-wire-adapter-usages](https://github.com/salesforce/eslint-plugin-lwc/blob/master/docs/rules/no-unexpected-wire-adapter-usages.md) rules to the base config.

feat(base-config): add no-unknown-wire-adapters and no-unexpected-wire-adapter-usages

---

.circleci/config.yml
package.json
yarn.lock

This PR adds support for ESLint 7 to this package:
- Update dependencies to make them compatible with ESLint 7
- Add build step in CI to check if package work on both ESLint 6 and ESLint 7
Fixes #38

chore: Add ESLint 7 support

---

package.json
recommended.js
test/recommended.js
yarn.lock

In this PR:
1. Configures `lwc/valid-api` in the recommended preset, disallowing mixed use of upper case and underscore in API fields and methods.
2. Adds `lwc/prefer-custom-event` to the recommended preset.
3. Adds `lwc/no-dupe-class-members` to the recommended preset.

chore: upgrade @lwc/eslint-plugin-lwc and add rules to recommended preset

---

package.json
recommended.js
test/recommended.js
yarn.lock

Enabled by default since this violation currently throws an exception during runtime.

chore: enable no-attributes-during-construction

---

lib/defaults.js

Avoids the "Parsing error: Cannot use the decorators and decorators-legacy plugin together" parsing error when the consuming application uses the legacy decorators plugin. This configuration causes no issues when the consuming application is using the new decorators plugin.

fix: use backwards-compatible configuration for decorators plugin

---

base.js

As referenced in Issue #52 : adding a new wire adapter to the known list. ✅

feat: add the `commerce/cartApi:CartSummaryAdapter` to the known wire adapter list

---

package.json
yarn.lock

v0.12.2 gets picked up instead of v0.12.2-232.0 because the latter isn't semver compliant.

fix: use exact version

---

base.js

This `commerce/cartApi:CartSummaryAdapter` was added as part of https://github.com/salesforce/eslint-config-lwc/pull/53

fix: enforces CartSummaryAdapter to be used only with wire decorator

---

README.md
package.json

The ESLint programming model considers shareable configs and plugins as peer dependencies so the way we currently have `eslint-plugin-lwc` as a dependency of `eslint-config-lwc` only works when they are treated as peers by package managers such as npm and yarn through hoisting. This breaking change removes plugins as dependencies and declares them as peer dependencies that must be installed by users of this package.
We can remove these peer dependencies when we upgrade to eslint v8 which will implement [a new configuration system](https://github.com/eslint/eslint/issues/13764#issuecomment-713031703) that will allow us to treat plugins as dependencies.
References:
- https://github.com/eslint/eslint/issues/3458
- https://github.com/eslint/eslint/issues/2518

chore: convert plugin dependencies to peer dependencies

---

README.md
base.js
package.json
recommended.js
test/recommended.js
test/utils.js
yarn.lock

This PR integrates `@salesforce/eslint-plugin-lightning` new plugin to the repository. It adds the `@salesforce/lightning/valid-apex-method-invocation` to the recommended set of rules. 
**⚠️ This is PR introduces a breaking change as it requires `@salesforce/eslint-plugin-lightning`  to be installed as peer dependency ⚠️**

[BREAKING] Integrate @salesforce/eslint-plugin-lightning

---

package.json
test/extended.js
test/recommended.js
yarn.lock

This PR removes peer dependency semantic versioning for `eslint-plugin-import` and `eslint-plugin-jest`. This package doesn't rely on a specific version of those package as it only consumes the recommended configuration. 
After speaking with @ravijayaramappa I don't think the idea that this package should [restrict the usage of those peer dependencies to what is tested](https://github.com/salesforce/eslint-config-lwc/pull/58#discussion_r614235829) is incorrect. At the end of the day, those peer dependencies are not tested in this project. 
Giving the downstream consumers more control over which version they want to use would help them migrate at their own pace.

Lossen peer-dependency semver

---

README.md
i18n.js
package.json
test/i18n.js

Adding configuration for I18N rules. This is to promote the use of @salesforce/localizer as a best practice for I18N in LWC:
Note that this change needs https://github.com/salesforce/eslint-plugin-lwc/pull/52 to be merged first.
I18N configuration contains following rules:
- `prefer-localizer`: give warnings (not errors), and suggest to use localizer over using Intl directly
- `no-moment`: discourage use of moment (again as a warning)
- `no-aura-localization-service`: will mark references to `$A.localizationService` as warnings (this is only used in Core).
This is 1st change, where existing configurations are untouched:
- Add a new `i18n` config that only includes those i18n rules - that can be added on top of other configs by devs who need it (e.g. in base-components) or want to test it. …

feat: adding i18n rule set

---

.circleci/config.yml
package.json

When installing this package with eslint@6, the following message gets printed. ([example](https://app.circleci.com/pipelines/github/salesforce/eslint-config-lwc/155/workflows/04df0e57-427a-414a-ac69-37505747dbdb/jobs/274/parallel-runs/0/steps/0-104))
```
warning " > @babel/eslint-parser@7.13.14" has incorrect peer dependency "eslint@>=7.5.0".
warning " > @salesforce/eslint-plugin-lightning@0.1.0" has incorrect peer dependency "eslint@^7".
```

fix: Drop support for eslint@6

---

base.js

This PR registers/adds the publicly available commerce wire adapters of RP 234:
* `commerce/contextApi/AppContextAdapter`
* `commerce/contextApi/SessionContextAdapter`
* `commerce/productApi/ProductAdapter`
* `commerce/productApi/ProductCategoryAdapter`
* `commerce/productApi/ProductCategoryHierarchyAdapter`
* `commerce/productApi/ProductCategoryPathAdapter`
* `commerce/productApi/ProductPricingAdapter`
* `commerce/productApi/ProductSearchAdapter`

feat(commerce): register 234 commerce adapters

---

base.js

This PR updates the registered publicly available commerce wire adapters of RP 234:
* `commerce/cartApi/CartItemsAdapter` as it just got provided publicly today
* `commerce/productApi/ProductSearchAdapter` had to be removed as it turned out that the underlying Connect API is not meant to be consumed publicly, even though it is of course public as a Connect API 🤦. Apparently it got created by the holy ghost as no one wants to have been it...

feat(commerce): updated registered 234 commerce adapters

---

package.json
recommended.js
test/recommended.js
yarn.lock

Add the newly created rule [no-template-children ](https://github.com/salesforce/eslint-plugin-lwc/commit/b916a0b0cd53ec35fde42eeed96b355bae080716) into the recommended configuration.

feat: add no-template-children rule to recommended configuration

---

package.json
recommended.js
test/recommended.js

This PR disables the `lwc/no-dupe-class-members` rule when running ESLint v8. It prevents reporting twice the same duplicate field error message. 
Address this issue on the original ESLint v8 upgrade https://github.com/salesforce/eslint-config-lwc/pull/77#discussion_r746387800

fix: Avoid duplicate no-dupe-class-members warning with ESLint v8

---

base.js

[@W-10448072](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000gGWAcYAO/view)
Description
expose getListInfosByName wire adapter in lightning
Changes in this pull request
Added customer-facing lint rule to getListInfosByName wire adapter

Add customer facing lint rule to getListInfosByName Adapter

---

base.js

Most of them are new in Summer '22; `getDataflows` and `getRecipeNotification` where added in Spring `22.
@W-10758280
cc: @rdubovetskyi, @danny6514, @lindsey-burnett, @karihotchkiss

Add new public analytics wire adapters

---

base.js
package.json
test/base.js
yarn.lock

Upgrade to `@lwc/eslint-plugin-lwc` v1.3.0 to benefit from the pattern matching support that got added recently. Adjust the `base.js` configuration to whitelist the `experience` and `commerce` API related wire adapters in the rule `@lwc/lwc/no-unknown-wire-adapters` and respectively blacklist the same adapters in the rule `@lwc/lwc/no-unexpected-wire-adapter-usages`.

feat: add support for pattern matching in rule no-unexpected-wire-adapter-usages

---

base.js

This adds more restrictive whitelisting/blacklisting patterns to prevent falsely blocked `commerce` or `experience` API exports.

fix: fix whitelisted commerce and experience wires @W-11390210

---

.circleci/config.yml

Temporarily remove auto-deploy while we find a solution for W-11138153.
Once W-11138153 is resolved, we can add this workflow back in. In the meantime, manual publish using `yarn release:publish` is sufficient.

fix: temporarily remove auto-deploy @W-11138153

---

.circleci/config.yml

As of 2023-09-11, v16 is EOL and v18 is LTS

chore: node v18.18.0

---

package.json

`ssr.js` is not included in what's shipped to NPM.

chore: include ssr.js in package.json's files[]

---

README.md
base-ts.js
extended-ts.js
i18n-ts.js
lib/typescript.js
package.json
recommended-ts.js
ssr-ts.js
test/base.js
test/extended.js
test/i18n.js
test/recommended.js
test/ssr.js
test/utils.js
yarn.lock

Properly setting the right `parserOptions` to support TypeScript is tedious, so this PR adds new configs that do that for you. Each existing config now also has a `-ts` flavor that supports TypeScript. For example, to use the recommended rules in a TypeScript project, use the `recommended-ts` config.

feat(ts): add configs that support TypeScript @W-16036296@
